// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGJGArnwPHuvN-lM-qzuuY2ErQ0SJX3EQ',
    appId: '1:1081993030727:web:a1be99155dadd8e42a1562',
    messagingSenderId: '1081993030727',
    projectId: 'delievry-4ab12',
    authDomain: 'delievry-4ab12.firebaseapp.com',
    storageBucket: 'delievry-4ab12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHpjFCRTh2x_yRTqxGeSCAoxWMP4SCn4k',
    appId: '1:1081993030727:android:27cdbce84e5161842a1562',
    messagingSenderId: '1081993030727',
    projectId: 'delievry-4ab12',
    storageBucket: 'delievry-4ab12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEZjl7UTXzzSYRP6pEvCOBCt_4ZIvI6UU',
    appId: '1:1081993030727:ios:e8a393cf0e0e76102a1562',
    messagingSenderId: '1081993030727',
    projectId: 'delievry-4ab12',
    storageBucket: 'delievry-4ab12.appspot.com',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEZjl7UTXzzSYRP6pEvCOBCt_4ZIvI6UU',
    appId: '1:1081993030727:ios:0f985e857a50a7e32a1562',
    messagingSenderId: '1081993030727',
    projectId: 'delievry-4ab12',
    storageBucket: 'delievry-4ab12.appspot.com',
    iosBundleId: 'com.example.delivery.RunnerTests',
  );
}
